### ISSUE TITLE
How to use dimensions script ?

### ISSUE THREAD

**Issue by ketourneau** [IFCjs/web-ifc-viewer#103]
Hi,

How we can use dimensions.ts in viewer/src/display/dimensions/dimensions.ts ?
Do you have any exemple (from https://twitter.com/ifc_js/status/1456318465921454085?s=20) ?

Best regards,

**Comment by REO1965** [comment]
This should get you going :
```javascript
import { IfcDimensions } from 'web-ifc-viewer/dist/components/display/dimensions/dimensions';

ifcDimensions = new IfcDimensions(viewer.context);
ifcDimensions.active = true;
ifcDimensions.previewActive = true;

ifcDimensions.create();
