### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'count')

### ISSUE THREAD

**Issue by timcash** [IFCjs/web-ifc-viewer#104]
```
main.js:91673 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'count')
```

when loading and many others
http://openifcmodel.cs.auckland.ac.nz/Model/Details/380

**Comment by agviegas** [comment]
Hi! Unfortunately, this model is IFC2x2 (quite old), and we support IFC2x3, IFC4 and beyond 😊
