### ISSUE TITLE
Clipping plane bug

### ISSUE THREAD

**Issue by pierremonico** [IFCjs/web-ifc-viewer#111]
I can easily add a clipping plane by doing something along the lines of:
```js
  const cutElement = async () => {
    await viewer.clipper.createPlane();
  };
``` 
This works without a problem. However, as soon as I hover my mouse above one of the clipping plane arrows I get a console error:
```console
IFCLoader.js:520 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'mesh')
    at SubsetManager.getSubset (IFCLoader.js:520:1)
    at IFCManager.getSubset (IFCLoader.js:2967:1)
    at ClippingEdges.newSubset (clipping-edges.js:144:1)
    at async ClippingEdges.newStyle (clipping-edges.js:84:1)
    at async ClippingEdges.createDefaultStyles (clipping-edges.js:115:1)
    at async ClippingEdges.updateEdges (clipping-edges.js:60:1)
``` 

The clipping plane is also extremely laggy (can't really be used). 

I tried with the same model on older versions (with your `simple-react` example) and it all works, so not due to the model. 

I am using `web-ifc-viewer@^1.0.137`.

Let me know if you need me to provide you more information.

EDIT: updated to `web-ifc-viewer@^1.0.168` but it didn't help.

**Comment by pierremonico** [comment]
After some debugging, I figured out that that the problem is closely tied to `createDefaultStyles()`. It's a bit hard to dive into the whole logic of the library within a few hours but basically it seems that when trying to `newSubset()` with the first seven categories, if you have a model that doesn't have any of those then you're trying to `getSubset()` a subset that doesn't exist. Creating default styles was a good intention but seems to mess things up here :) 

I tried it out with another model that has some of these IFC types and the bug disappears.

**Comment by agviegas** [comment]
Hey! You can use `ClippingEdges.createDefaultIfcStyles = false` to prevent the viewer from creating the default styles, and then create the styles with the categories you want.

**Comment by pierremonico** [comment]
Thanks, but where do I import that from / when do I set it? I see it in the repo source but when `dist`ributed I only find it in "web-ifc-viewer/dist/components/display/clipping-planes/clipping-edges" and it doesn't carry the `createDefaultIfcStyles` static option.

**Comment by pierremonico** [comment]
I am super confused by the available options. In the source I see only `clipping-edges.ts` in which `ClippingEdges.createDefaultIfcStyles` is an attribute. 

When I install the package (not using TS), I have:
- `clipping-edges.js` in which `ClippingEdges.createDefaultIfcStyles` is a method
- `clipping-edges.d.ts` in which on `ClippingEdges` there is declared `private createDefaultStyles;`

I don't have too much experience with TS and am not using it on this project, so there is probably some build step/generation going on here that I am missing, but it would be good to know how to make it work with "plain" JS. 

Thanks!

**Comment by pierremonico** [comment]
Solved! Devil in is in the detail: `createDefaultIfcStyles` vs `createDefaultIfcStyles` 🤦‍♂️ 

On a side note: IMHO I find unintuitive to have a default setting that will generate a bug for some models. Personally I would rather have this set to `false` by default. 

Thanks again for the help!
