### ISSUE TITLE
Disable DropboxAPI from making request by default

### ISSUE THREAD

**Issue by eng-luciano-julien** [IFCjs/web-ifc-viewer#112]
Hi,

Initiating IfcViewerAPI it initialize DropboxAPI and load dropbox content even if I don't use it.
It would good to load dropbox content only if choosed by the developer with an option in ViewerOptions.

**Comment by agviegas** [comment]
Hi, solved from 1.0.169!

**Comment by eng-luciano-julien** [comment]
Thank you!
