### ISSUE TITLE
"Uncaught (in promise) TypeError: this context is undefined" in prePickIfcItem

### ISSUE THREAD

**Issue by m1900** [IFCjs/web-ifc-viewer#114]
I keep getting the mentioned error in my application based on this post [https://ifcjs.github.io/info/blog/Build%20a%20CDE%20in%2030%20minutes/ ](https://ifcjs.github.io/info/blog/Build%20a%20CDE%20in%2030%20minutes/ ) (I left out the Google Drive part and select an IFC using a simple input element instead). Version of web-ifc-viewer used is 1.0.168.

An extract of my code can be found in my [ProtoIfcViewer repo](https://github.com/m1900/ProtoIfcViewer.git).

**Comment by simplynail** [comment]
Hi @m1900 , I was able to solve the problem by swapping `web-ifc.wasm` file inside my app with the most recent builds
(found here https://github.com/IFCjs/web-ifc-viewer/tree/master/example/files - I've copied both web-ifc.wasm and web-ifc-mt.wasm, I'm going through the documentation but have not yet found the purpose for -mt.wasm file). 

For some reason the original google-drive-viewer example didn't work for me with original .wasm file from https://github.com/IFCjs/hello-world/tree/main/examples/web-ifc-viewer/google-drive-viewer/wasm

**Comment by simplynail** [comment]
sorry Guys, my bad - I've noticed that the only thing that swapping `.wasm` did for me was that the model actually got loaded and shown in the browser, but the `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'prePickIfcItem') (main.js:91596:33)` error is still there

**Comment by agviegas** [comment]
Hi, this is probably because you are binding the prepick function to an event directly, like this:
```js
window.onmousemove = viewerAPI.IFC.selector.pickIfcItem;
```
Because the function is executed by the eventhandler, the reference to `this` is lost. You could try something like this:
```js
window.onmousemove = () => viewerAPI.IFC.selector.pickIfcItem();
```
Let me know how it goes!

**Comment by m1900** [comment]
Hi Antonio, this solved my problem 😃. It makes sense that this is the way to bind the prepick function. 

I think [https://github.com/IFCjs/hello-world/blob/main/examples/web-ifc-viewer/google-drive-viewer/main.js](https://github.com/IFCjs/hello-world/blob/main/examples/web-ifc-viewer/google-drive-viewer/main.js) needs to be corrected.

**Comment by simplynail** [comment]
hi,
worked for me as well (for what is worth I needed to do `window.onmousemove = () => viewer.IFC.selector.prePickIfcItem();` while earlier instantiating viewer as `const viewer = new IfcViewerAPI();`
