### ISSUE TITLE
[Feature request] Drag drop support

### ISSUE THREAD

**Issue by chaitanya-deep** [IFCjs/web-ifc-viewer#130]
The viewer currently does not seem to support dragging an IFC file to the viewer region to open it.
It's just a better UX but helps alleviate the problem of trying to navigate through folders.

P.S: I'm pleasantly surprised it supports adding multiple IFC files at once

**Comment by tonyk24** [comment]
Hello, I started working on this. Is it still a good idea to have it in the example? Or should it be in an "editor".

**Comment by agviegas** [comment]
Hey @tonyk24 I think this would be a fantastic addition to the editor. We'll start the repository these days. If you could create it there then, it would be super great. Thanks a lot for this!
