### ISSUE TITLE
[Feature request]  SEO improvements

### ISSUE THREAD

**Issue by chaitanya-deep** [IFCjs/web-ifc-viewer#131]
The landing page(https://ifcjs.github.io/info/) does not seem to have a link to the web viewer and only has one for the docs.

The web viewer seems to be the best solution out there and the one with least friction to simply see an IFC file but a google search for "View IFC online" doesn't show it anywhere in the first page for me.

The ideal situation I think would be similar to how Google shows https://gltf-viewer.donmccurdy.com/ for "View gltf online"

**Comment by agviegas** [comment]
We are making a new landing page and we'll make sure to include a link to a viewer, or embed it directly 🙂

**Comment by arunkvijay** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @arunkvijay! Thanks for taking this bounty! The due date is January 2, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by arunkvijay** [comment]
@agviegas I am planning to add a `button` that allow users to upload an ifc file. Should I add this button to the `header` next to the `Get Started` button or should it be a different section added below the `header` section.

**Comment by agviegas** [comment]
@arunkvijay A button in the top bar called "Demo" (next to _Community_) should be good!

**Comment by arunkvijay** [comment]
::extend

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::extend

Hi, @arunkvijay! The due date is successfully extended by 21 days to January 23, 2023 UTC.

**Comment by agviegas** [comment]
### 🔴🔴🔴

Hi, @arunkvijay! The date is past due, your assignment has been revoked. It’s now available for anyone to take.

**Comment by arunkvijay** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @arunkvijay! Thanks for taking this bounty! The due date is March 1, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by arunkvijay** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @arunkvijay! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by aka-blackboots** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @aka-blackboots! Thanks for taking this bounty! The due date is May 4, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
::done

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::done

Hi, @aka-blackboots! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by aka-blackboots** [comment]
::expense::134263

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::134263

Hi, @aka-blackboots! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @aka-blackboots! Your [expense](https://opencollective.com/ifcjs/expenses/134263) has been approved!

**Comment by agviegas** [comment]
### 🎉🎉🎉

Hi, @aka-blackboots! Thanks for your contributions! The reward of this bounty has been transferred to your Open Collective account.
