### ISSUE TITLE
[Bug report] Web viewer crash on cancelling multiple IFC file loads

### ISSUE THREAD

**Issue by chaitanya-deep** [IFCjs/web-ifc-viewer#132]
Steps to reproduce:
- Open an IFC file. The file loads fine.
- Click on Open for a second time
- Cancel without choosing a file

Result:
The UI becomes responsive and stuck at Loading

Expected outcome:
It should just let the user interact with the already loaded file

**Comment by aozien** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @aozien! Thanks for taking this bounty! The due date is January 8, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by aozien** [comment]
Hey @agviegas ,  can you mark this bounty as done?

**Comment by agviegas** [comment]
::done

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::done

Hi, @aozien! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by aozien** [comment]
::expense::114946

**Comment by agviegas** [comment]
### 🔴🔴🔴

> ::expense::114946

Hi, @aozien! We cannot find a new expense with that invoice number. Please re-check the invoice number and re-send the command using the correct one.
