### ISSUE TITLE
Openning large civil 3d models - camera fitview

### ISSUE THREAD

**Issue by Kubica91** [IFCjs/web-ifc-viewer#134]
Hi, there is some problem with opening Civil 3D models. This model is several kilometers large and the ifc camera in browser does not want to capture this model. I thing, the camere are dealing with occlusion culling - that means model is in scene, but too far to view it by camera.  I tried set all meshes to .frustumCulled = false, but it doesnt work.... You can find this fix on three.js stackoverflow. 
https://stackoverflow.com/questions/59727192/threejs-disable-frustum-culling-for-some-objects
I tried in code fit camera: ifcCamera.cameraControls.fitToBox and ifcCamera.cameraControls.fitToSphere, max and min distance, but still nothing.
Image for example:
![image](https://user-images.githubusercontent.com/62777372/170047927-1cdbd505-ad72-436a-9e2d-e377c57cc3f9.png)

The second way to work around this oversight, I tried to scale model geometry/scene. But there was another problem with selecting elements with doubleclick. Hitbox retains its original size and the camera fitview toi this original hitbox..  
Image for example:
![obrázek_2022-05-24_152304301](https://user-images.githubusercontent.com/62777372/170045434-2bd8c3ae-4ca6-4d61-8a93-2d29dbbec1b1.png)

Can you please look at this issue. Thank you.

**Comment by agviegas** [comment]
Hey, did you try [bringing the model to the origin](https://ifcjs.github.io/info/docs/Guide/web-ifc-three/api#applywebifcconfig)?

**Comment by Kubica91** [comment]
yes, i have this in code:
![image](https://user-images.githubusercontent.com/62777372/170451749-c09635f3-4279-4c13-a6a6-c7be57edf79a.png)
I tried  COORDINATE_TO_ORIGIN: false, too

Here are three pictures about this problem. Everything can be seen in the first picture. After zooming out, the model starts to disappear (second image) and in the next zoom out it disappears completely (third image).
What can be seen in the picture is not the whole model, but only a part...
![image](https://user-images.githubusercontent.com/62777372/170452309-cbc4e35a-7c37-46ba-b1ef-a875023f2f14.png)

**Comment by agviegas** [comment]
The problem then is that the model dissapears? Have you tried changing the camera [far attribute](https://threejs.org/docs/#api/en/cameras/PerspectiveCamera.far)?

**Comment by Kubica91** [comment]
Yes, it is. I tried this, but result is the same..
![image](https://user-images.githubusercontent.com/62777372/170928455-6b201292-da98-492e-8f58-f84f624e9626.png)
in the viewer is something like a white wall, which overlaps the model on the size of the zoom

**Comment by agviegas** [comment]
@Kubica91 can you send us that IFC?

**Comment by Kubica91** [comment]
Yes of course, but not here. Can you send me please your email or contact me and I'll send it to you. 
My email: petran@proconom.cz

**Comment by agviegas** [comment]
Hey @Kubica91 I've taken a look at this in BIMvision and it's the same, so it looks like the problem is in the file and not in IFC.js. Were you able to open it successfully with other viewers? 

![image](https://user-images.githubusercontent.com/56475338/172694324-a3124483-592b-4c8f-afa3-fa644d008f34.png)

**Comment by Kubica91** [comment]
Hi @agviegas, we have our viewer, that is base from Autodesk Forge and it allow you to fit camera to all model pieces (geometries). 
![image](https://user-images.githubusercontent.com/62777372/172707244-e9ef4671-9758-4da1-97a8-cfdc61f014f6.png)

IFC.js can open model succesfully, but camera has scroll limitation (with mouse wheel) and i dont have option to look at the main piece of model. This is the maximum scroll IFC.js in your demo: https://ifcjs.github.io/web-ifc-viewer/example/index.  
![image](https://user-images.githubusercontent.com/62777372/172703966-97091522-83f3-4b1c-a721-8b917609433f.png)

I know this model isnt the normal ifc model.... It is automatically render from Autodesk Civil application... 
It would be best, when the IFC.js viewer allows you to fit the camera to all pieces of the model, so then the user can double-click  left mouse button on required piece and zoom (fit) camera to it.

**Comment by agviegas** [comment]
Hi @Kubica91. I'm not sure if you are trying to use the viewer as an end user application. For your information, it's just a small demo for demonstrating what can be done with the library. It's not intended to be used as an end-user tool, and there are no plans of doing it more convoluted, as its main purpose is getting started with this repository.

If you are creating a BIM application using this repository, you can control the camera behaviour through `ifcViewerAPI.context.ifcCamera.cameraControls`. We are using [this library](https://github.com/yomotsu/camera-controls) for this. If you have any question regarding the use of the library for development, let us know!
