### ISSUE TITLE
Post-production too dark for electricals models

### ISSUE THREAD

**Issue by eng-luciano-julien** [IFCjs/web-ifc-viewer#146]
Hi,

For some models as electricals models, the result of post-production is not good. May it needs to be ajusted.
![image](https://user-images.githubusercontent.com/82835289/178866594-47ab5a93-2936-41d7-8999-915ac6bc4661.png)
![image](https://user-images.githubusercontent.com/82835289/178866813-b7c9a97f-90b9-4d43-ba49-33a603a94e4b.png)

**Comment by agviegas** [comment]
Hi! The postproduction layer is an HTML img element on top of the Three canvas. One way to adjust it would be to take that element and add some transparency. You can find it in `webIfcViewer.context.renderer.postProduction.tempRenderer.domElement`. Hopefully this helps!
