### ISSUE TITLE
Feature request: disposal of a single model

### ISSUE THREAD

**Issue by m1900** [IFCjs/web-ifc-viewer#147]
In my application I want to show only one model at a time. As soon as the user selects a different model, the old model should be disposed of so that the memory it occupys is cleared, while the scene and all other objects remain. I need a method that handles the disposal of the model for me, something like IfcManager.remove(model).

**Comment by agviegas** [comment]
Hi, you can use `webIfcViewer.dispose()`. Keep in mind that it is your responsibility to remove the models/materials from any object or array that you create; otherwise, the memory won't be able to be disposed of. Cheers!

**Comment by aka-blackboots** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @aka-blackboots! Thanks for taking this bounty! The due date is December 23, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by aka-blackboots** [comment]
::drop

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @aka-blackboots! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by D4ve-R** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @D4ve-R! Thanks for taking this bounty! The due date is February 21, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by D4ve-R** [comment]
@agviegas can be marked as done, github's resolve comment somehow breaks the bot

**Comment by agviegas** [comment]
### 🔴🔴🔴

Hi, @D4ve-R! The date is past due, your assignment has been revoked. It’s now available for anyone to take.

**Comment by agviegas** [comment]
Hey @D4ve-R if you take this, I'll mark it as done. By the way, reviewing this code, I don't see if you are [disposing the geometry and materials](https://threejs.org/docs/#manual/en/introduction/How-to-dispose-of-objects) to prevent a memory leak. Are you doing that somewhere? That's a necessary step to get rid of models. Cheers!

**Comment by aka-blackboots** [comment]
@agviegas, looking at commits. Is this the step you're referring to? -> https://github.com/IFCjs/web-ifc-three/pull/144/commits/8149440fcefa01a5000683b73d80a92ae8e9f8d2

**Comment by agviegas** [comment]
@aka-blackboots that's right, thanks!

**Comment by D4ve-R** [comment]
@agviegas, not sure right now, will look into this.

**Comment by D4ve-R** [comment]
should be all good
https://github.com/IFCjs/web-ifc-viewer/blob/9ce3a42cb8d4ffd5b78b19d56f3b4fad2d1f3c0e/viewer/src/components/ifc/ifc-manager.ts#L249

calls web-ifc-three's close method which handles disposal of geo & material

**Comment by D4ve-R** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @D4ve-R! Thanks for taking this bounty! The due date is March 19, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::done

Hi, @D4ve-R! Thanks for your contributions! Please submit an expense to IFC.js Open Collective. Then, tell us the invoice number via the `::expense::_____` command (replace the `_____` with the invoice number).

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::expense::125715

Hi, @D4ve-R! Thanks for the confirmation! We’ll proceed to review the expense. Once it’s approved, the payment will be scheduled.

**Comment by agviegas** [comment]
### 🟢🟢🟢

Hi, @D4ve-R! Your [expense](https://opencollective.com/ifcjs/expenses/125715) has been approved!

**Comment by agviegas** [comment]
### 🎉🎉🎉

Hi, @D4ve-R! Thanks for your contributions! The reward of this bounty has been transferred to your Open Collective account.
