### ISSUE TITLE
Rendering isseus on every IFCjs example on github

### ISSUE THREAD

**Issue by ngorlani** [IFCjs/web-ifc-viewer#151]
Hi,
I'm trying to test an IFC model but every example in "IFCjs/hello-world" project and "IFCjs/examples" project have **severe** geometrical problems:

![image](https://user-images.githubusercontent.com/91492685/180968181-83227dc5-229c-4eb0-85a2-6dca262fedc3.png)

I try the same IFC model using the project "IFCjs/web-ifc-three/example/" and **here there isn't sever geometrical problems**:

![image](https://user-images.githubusercontent.com/91492685/180968609-3f4646b1-93c2-4f97-a554-394ec4aac4db.png)

I have try to allign the dependency (web-ifc, web-ifc-three, web-ifc-viewer, three ...) and I have replaced the wasm files with "https://github.com/IFCjs/web-ifc-three/tree/main/example/*.wasm" but the problems was not solved.

@agviegas, can be a problem solved with web-workers but not with the base ifcjs configuration?

thanks
N.

**Comment by ngorlani** [comment]
If I put an empty list of OptionalCategories in the ParserAPI the geometrical problems disappear:

`this.ifcViewer?.IFC.loader.ifcManager.parser.setupOptionalCategories({ });`

why??

**Comment by agviegas** [comment]
Hi, IFC.js generates the IfcSpace items of the IFC by default. Probably that is an IfcSpace that you missed. You can make them active or inactive using that method. For example:

```js
import { IFCSPACE, IFCOPENINGELEMENT } from 'web-ifc';

this.ifcViewer?.IFC.loader.ifcManager.parser.setupOptionalCategories({
     [IFCSPACE]: false,
     [IFCOPENINGELEMENT]: false
 });
```

Cheers!
