### ISSUE TITLE
Processing IFC models that do not contain IFCBuilding

### ISSUE THREAD

**Issue by aybond** [IFCjs/web-ifc-viewer#161]
### Description

When I try to get all the properties of an IFC model that does not contain IFCBuilding, an error occurs:
![](https://media.discordapp.net/attachments/912752967537537075/1025414278456561794/Screenshot_from_2022-09-30_16-28-05.png)
IFC models of strict structure are successfully processed.

A problem appears when exporting a model as a GLTF object. The model loads and displays successfully on the canvas, but the above error occurs when exporting, namely when retrieving properties:
`await ifcViewer.current.IFC.properties.serializeAllProperties(
      model
);`

### Expected Behavior

**serializeAllProperties** method successfully returns the result regardless of the presence that the IFC-model structure is strict.

### Steps to Reproduce

- **loadIfcUrl** [https://cdn.discordapp.com/attachments/912752967537537075/1025414451165413386/060_3.ifc](url)
- **serializeAllProperties** of loaded IFC model

### Environment

- "three": "0.135.0"
- "web-ifc-three": "0.0.115"
- "web-ifc-viewer": "1.0.176"

**Comment by Andyan1966** [comment]
👍

**Comment by aka-blackboots** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @aka-blackboots! Thanks for taking this bounty! The due date is December 23, 2022 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::drop

Hi, @aka-blackboots! Thanks for giving it a try! It’s now once again available for anyone to take.

**Comment by D4ve-R** [comment]
::take

**Comment by agviegas** [comment]
### 🟢🟢🟢

> ::take

Hi, @D4ve-R! Thanks for taking this bounty! The due date is February 21, 2023 UTC.

If you need to submit some pull requests (PR) to complete the tasks, make sure that the last and only the last PR has a title that either starts with the bounty ID or is exactly the same as the bounty name. After the PR is merged, this bounty’s status will automatically changed to done.

If you do not need to make a PR, tell the manager @agviegas to run `::done` command after your tasks is confirmed to be done.

Good luck!

**Comment by D4ve-R** [comment]
@agviegas can be marked as done, using github's resolve comment somehow breaks the bot 🤔

**Comment by agviegas** [comment]
### 🔴🔴🔴

Hi, @D4ve-R! The date is past due, your assignment has been revoked. It’s now available for anyone to take.

**Comment by agviegas** [comment]
::done

**Comment by agviegas** [comment]
Hey @D4ve-R sorry for the delay. If you take this again, I'll mark this as done. Thanks a lot!
