### ISSUE TITLE
Request version that runs  inNodeJS without browser

### ISSUE THREAD

**Issue by rubit0** [IFCjs/web-ifc-viewer#167]
I need to convert IFC to GLTF in a nodejs service but unlike the core web-ifc pacjage I can't make this one to run in nodejs.

Thank you!

**Comment by agviegas** [comment]
Hi @rubit0 unfortunately web-ifc-viewer is not compatible with node.js and there are no plans to do it. You can use [web-ifc](https://github.com/IFCjs/web-ifc) or [web-ifc-three](https://github.com/IFCjs/web-ifc-three) for this. We might make a [component](https://github.com/IFCjs/components) to make this in node easily at some point. Cheers!

**Comment by whathecker** [comment]
Thanks for the pointer!
