### ISSUE TITLE
Problem picking columns in a plan view

### ISSUE THREAD

**Issue by RASRC** [IFCjs/web-ifc-viewer#183]
Hello everyone.

Mi name is Rodrigo, student from the IFC.js Crash Course.

During the making of the final exercise, I found some problems picking columns elements in plan views, using web-ifc-viewer.

Revieing the IFC file in BIM Vision, the structure appears to be ok.

Attached to this message you will find the IFC file and a couple of screenshots.

Thank you.

Best regards.

[Attachments.zip](https://github.com/IFCjs/web-ifc-viewer/files/10593548/Attachments.zip)

**Comment by agviegas** [comment]
Hi, the reason columns can be picked in floorplans is that the Three.js picker doesn't work with the backfaces of items. You can try making the material of the floorplans two-sided (`material.side = 2`) and see if it helps. If not, it means that the lower face of the columns are below the slab of that floor, and the current floorplan system won't allow it to work.

**Comment by RASRC** [comment]
Hi @agviegas. I put in practice your suggestion and it works perfect.

Thank you!

![Cap01](https://user-images.githubusercontent.com/117295504/216937453-0b6de0b9-b0e8-40f5-9f83-4427ba456da0.png)
