### ISSUE TITLE
RuntimeError: abort(LinkError: WebAssembly.instantiate(): Import #0 module="a" function="a" error: function import requires a callable)

### ISSUE THREAD

**Issue by Hilicot** [IFCjs/web-ifc-viewer#189]
Hello,
I am trying to use `web-ifc-viewer` inside a React-typescript web app. By debugging I managed to set the correct path to the .wasm files (taken directly from the `node_modules/web-ifc` folder) : `viewer.IFC.setWasmPath("../../wasm/");`

However, now I get the error:

```
index.js:1 
        
       RuntimeError: abort(LinkError: WebAssembly.instantiate(): Import #0 module="a" function="a" error: function import requires a callable). Build with -s ASSERTIONS=1 for more info.
    at abort (web-ifc-api.js:6627:1)
    at web-ifc-api.js:6690:1
```

I checked the `wasmBinaryFile` variable and it does use the correct file.
I am using web-ifc-viewer^1.0.134, web-ifc^0.0.35

**Comment by agviegas** [comment]
Hi, did you check out our [React examples](https://github.com/ifcjs/examples)? Cheers!

**Comment by Hilicot** [comment]
I did check them, and they did not work, or if they did the result was a very flickery viewport.

I ended up explicitly calling `useWebWorkers()` to set the IFCWorker.js file, that I moved to the `public` folder.

I don't know if this is the intended way to solve it, but now it works...
