### ISSUE TITLE
2D plan navigation

### ISSUE THREAD

**Issue by ThomasvanHoutum** [IFCjs/web-ifc-viewer#195]
I was wondering how I can try out the 2D plan navigation that is described for this package, `multiple tools to easily build BIM tools, such as 3d dimensions, clipping planes, 2D plan navigation and generation, etc.`, or is it not in this project?

If not maybe someone can help me with another example that is creating or has created a 2D plan-viewer for IFC models. I am trying to figure out how to do it myself, but having an example, package or a pre-build viewer (that can be installed in another project) would be of much help.

Anything not IFCjs related is welcome as well!

Thanks in advance.

**Comment by agviegas** [comment]
Hi, you can find all the logic regarding 2d plans [here](https://github.com/IFCjs/web-ifc-viewer/tree/master/viewer/src/components/display/plans). We are now working on a [more modern repository](https://github.com/ifcjs/components) with tutorials to use all of this here. In the meantime, feel free to ask us anything you need!
