### ISSUE TITLE
Error while trying to run computeAllPlanViews

### ISSUE THREAD

**Issue by LeviSTA** [IFCjs/web-ifc-viewer#203]
Currently, we have a viewer made with web-ifc-three. And we're trying to use the IfcViewerAPI to computeAllPlanViews to generate plan views.

Our code that does this:
`await this.ifcViewerAPI?.plans.computeAllPlanViews(this.ifcModels[0].modelID);`

Where our IfcModel is loaded into the ifcModels array.

Currently we get this error when executing this:
![image](https://user-images.githubusercontent.com/123364333/230080377-3591b17c-b120-44a7-bea7-4ac582728254.png)

**Comment by ThomasvanHoutum** [comment]
I get the same error when following this code: https://github.com/IFCjs/hello-world/blob/main/examples/web-ifc-viewer/floorplans/app.js 
Is this an issue with the IfcViewerAPI?

**Comment by agviegas** [comment]
Web-ifc-viewer already contains web-ifc-three. When using web-ifc-viewer, you can access the instance of web-ifc-three like this: viewer.IFC.loader. Generally, importing web-ifc-three explicitly and using it separately is not recommended. 

In other words, you can't load a model in web-ifc-three, and then try to use the tools of web-ifc-viewer. Either you load the model in web-ifc-viewer, or you extract the tools that you want from web-ifc-viewer manually to create your own tools on top of web-ifc-three.

Might this be the cause of your problem @LeviSTA?
