### ISSUE TITLE
Spatial tree

### ISSUE THREAD

**Issue by xaibohphobiax** [IFCjs/web-ifc-viewer#205]
Is there already a way to display the spatial tree of an IFC file in the web viewer?

**Comment by Nomeon** [comment]
Yes, you can access the web-ifc-three function just as well from a project that is using web-ifc-viewer. You just need to call the `async IfcLoader.IfcManager.getSpatialStructure (modelID: number)` function from web-ifc-three.

You can access this, once you created a viewer and a model, by using a function like this: `yourViewer.IFC.loader.ifcManager.getSpatialStructure(yourModel)`

**Comment by LukasKStavario** [comment]
And can I get geometries of elements (not whole models) by some way?

**Comment by agviegas** [comment]
Please open new issues for new questions. Btw, not with web-ifc-viewer, but you can try to use [web-ifc](https://github.com/IFCjs/web-ifc), which is more flexible.

**Comment by xaibohphobiax** [comment]
There is also an implementation of the spatial tree here:
https://github.com/IFCjs/hello-world/tree/main/examples/web-ifc-viewer/spatial-tree
