### ISSUE TITLE
failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0

### ISSUE THREAD

**Issue by sushantc-inode** [IFCjs/web-ifc-viewer#206]
![image](https://user-images.githubusercontent.com/92144016/230555579-3d7e3ddd-ac86-4b0d-b991-9242d5bf6597.png)

**Comment by Nomeon** [comment]
Did you copy the web-ifc-mt.wasm and web-ifc.wasm from a source other than your project's node_modules/web-ifc? And some more info here would be handy; there is no code, no mention of a framework, no version, etc. Please help us help you.

**Comment by sushantc-inode** [comment]
I am using react 18.2.0 and "web-ifc": "0.0.33",
    "web-ifc-three": "0.0.124"

**Comment by sushantc-inode** [comment]
Got it,  I made mistake in webpack configuration, 

Thanks
