### ISSUE TITLE
Find duplicate geometry

### ISSUE THREAD

**Issue by LukasKStavario** [IFCjs/web-ifc-viewer#209]
I'm looking around the world of IFC.js. Can you advise me, I expected that there are many IFC model objects in the scene, but there is only one. I would like to go through all the children of the IFC model and compare their geometries - at the element level and list the elements with the same geometry, how do I do it?

**Comment by LukasKStavario** [comment]
I need to traverse not only scene, but then by models itself.

**Comment by agviegas** [comment]
@LukasKStavario Covering all possible use cases is going to be a bit hard for us, but you can use [web-ifc](https://github.com/IFCjs/web-ifc) to read the IFC nad generate the three.js geometry that suits your use case! 🙂

**Comment by LukasKStavario** [comment]
Thank you for your answer
