### ISSUE TITLE
web-ifc-viewer has been crashed after turn on  'useWebWorkers'

### ISSUE THREAD

**Issue by Balashoffs** [IFCjs/web-ifc-viewer#211]
Hello. Thanks for your job!

I have a problem, whed turn on 'useWebWorkers'

I got example at web-ifc-viewer last version, build it and the run with FiveServer.
Try to load ifc model and viewer has been crashed
What do I do wrong?

![image](https://user-images.githubusercontent.com/39002126/232044977-c96fc64c-0a4d-4e11-bf73-d6e3266ba474.png)

![image](https://user-images.githubusercontent.com/39002126/232043610-1c6b4c4a-fc61-4791-b19c-821557e79969.png)

**Comment by Nomeon** [comment]
It's probably the path to the wasm files. The way you set it up now is that the webworkers point to the `/files/` directory, but the setWasmPath is *relative* to that path. So now you're aiming it at the directory `/files/files/`. If the wasm files are in the same folder (so just `files`), you should probably use something along the lines of `viewer.IFC.setWasmPath('/')` (or `('./')`).

**Comment by Balashoffs** [comment]
I just uncomment 103 line at main.js at example project. At my project big Ifc models. That's why I want to explore this 
Without this - everything is ok
I copied wasm and webworkers files ifc-crash-course too - the same trouble.
So there is not at path to file

**Comment by Nomeon** [comment]
If you can send me the link to your repo I will take a look

**Comment by Balashoffs** [comment]
https://github.com/IFCjs/web-ifc-viewer/blob/master/example/main.js - it's from src of this repo.

**Comment by Balashoffs** [comment]
I found decision
