### ISSUE TITLE
serializeAllProperties does not work on Microstations IFC

### ISSUE THREAD

**Issue by LukasKStavario** [IFCjs/web-ifc-viewer#216]
Hi, I have a problem, I am trying to use viewer.IFC.properties.serializeAllProperties(model) and everything works fine on most models. If I want to load data from Microstations models, engine fails on get building height, can you repair it?

![image](https://user-images.githubusercontent.com/112091369/234833135-40e90b66-226b-4d39-9e60-4f4752e1eb3f.png)

**Comment by LukasKStavario** [comment]
@agviegas any info please? I think it is super simply, but I do not know where to locate it, can you help me please?

**Comment by agviegas** [comment]
Hi! Adapting this function for all possible IFC models might be a bit hard to achieve. 

You can easily create your own function to serialize the properties. You can take a look [here](https://github.com/IFCjs/web-ifc-viewer/blob/master/viewer/src/components/ifc/ifc-properties.ts#L32) for a reference and get all the properties you need from your model. Cheers!

**Comment by LukasKStavario** [comment]
Thank you for your answer!
