### ISSUE TITLE
IfcSelection Error: Cannot read properties of undefined (reading 'mesh')

### ISSUE THREAD

**Issue by SnGmng** [IFCjs/web-ifc-viewer#227]
Rendering the model works fine, but when doing a selection, i get the following error:
<img width="613" alt="Screenshot 2023-06-23 at 12 31 16" src="https://github.com/IFCjs/web-ifc-viewer/assets/38666407/bfcbf410-1670-4a0a-b61e-0fa3be94743d">

But as you can see, mesh and geometry is not undefined in the IFCModel:
<img width="735" alt="Screenshot 2023-06-23 at 13 35 48" src="https://github.com/IFCjs/web-ifc-viewer/assets/38666407/5953d427-612a-4cf6-a5ee-8f420a6f2bc6">

**Comment by SnGmng** [comment]
the cause seems to be that there is a model id mismatch between
`state.models[].modelID` (= 0)
and
`state.models[].mesh.modelID` (= 1)
as you can see here
<img width="946" alt="Screenshot 2023-06-23 at 14 32 30" src="https://github.com/IFCjs/web-ifc-viewer/assets/38666407/f63e2b50-bc1d-47be-ba7b-077d099d7d8d">

**Comment by agviegas** [comment]
Hey, are you using different instances of web-ifc-three / web-ifc-viewer, or using web workers to load models in parallel? If you are loading multiple models, are you awaiting the first to load before loading the second one?

**Comment by SnGmng** [comment]
Yes, thanks! I was using Angular and a component rerender triggered the model loading twice
Issue is gone now, thanks!
