### ISSUE TITLE
Request to Reupload Documentation for Web-Ifc-Viewer

### ISSUE THREAD

**Issue by LogicAddict** [IFCjs/web-ifc-viewer#241]
Hi, I am encountering issues while trying to utilize the web-ifc-viewer, and I believe that accessing its documentation would help resolve these problems. However, when attempting to visit the following URL: https://ifcjs.github.io/info/docs/Guide/web-ifc-viewer/Introduction, I receive a 404 error.

Could you please reupload or provide access to the documentation for the web-ifc-viewer?

Thanks in advance

**Comment by agviegas** [comment]
Hi @Muhammad-Anus-Developer this repository is deprecated and no longer maintained. It has been substituted by [components](https://github.com/IFCjs/components), which has more tools, is much more performant and has an updated [documentation full of tutorials](https://platform.thatopen.com/documentation). Cheers!

**Comment by LogicAddict** [comment]
Thanks for the update regarding the deprecation of the repository and the recommendation to use the new components. I appreciate the information, but I've been making good progress with web-ifc-viewer for my current project. I've already completed about 80% of the work, and I found it to be quite useful.

I need some assistance with certain functionalities like camera, highlight, and controls. In that regard, I would be grateful if you could share any relevant documentation or tutorials that could help me better understand and utilize these features within the web-ifc-viewer. Your guidance would be much appreciated as I aim to wrap up my project successfully.

Thanks again for your support!

**Comment by agviegas** [comment]
We are aware that this is not a desirable situation, but I started this project when I was learning to code, so of course it has many things to improve in its core design. Unfortunately, we don't have the financial/personal resources to work on this right now. The code is free and open source, so you are free to dig into it and even keep evolving it if you find it useful!

Even if you have a project with viewer, making the transition to components should be quite easy, as the API is similar.

**Comment by LogicAddict** [comment]
I hope that your project continues to be a helpful resource for those who use it. By the way checking out components demo, I am really inspired by it's design and performance. Is https://platform.thatopen.com/app code open source?

**Comment by agviegas** [comment]
Thanks @Muhammad-Anus-Developer! Each and every tool in the demo has a step-by-step tutorial in our docs. So if you follow all tutorials, you'll have a viewer just like the demo! 🙂 Needless to say, any new tool / feature we add to the demo will go to the tutorials as well.

**Comment by LogicAddict** [comment]
You're welcome, @agviegas! That's fantastic as it makes the learning process much smoother. I'll definitely dive into those tutorials to get the hang of it. Thanks for the helpful resources! 😊
