### ISSUE TITLE
Functions not yet implemented in IFCLoader Class

### ISSUE THREAD

**Issue by BrunoDG** [IFCjs/web-ifc-viewer#62]
When trying to implement the example "ifcjs-hello-world", some functions from the IFCLoader class were yet not implemented, like the "setWasmPath()" or the full implementation of the "parse()" function. 

Is there another way to implement the setWasmPath() inside the IFCLoader class?

**Comment by agviegas** [comment]
Can you please provide a minimal example where we can reproduce the error?

**Comment by BrunoDG** [comment]
Sure!

Currently, this is the actual IFCLoader class that's inside the _IFCLoader.d.ts_ declaration file located on "@types/three/examples/jsm/loaders":

```
import { Loader, LoadingManager, Object3D } from '../../../src/Three';

// tslint:disable-next-line:interface-name
export interface IFC extends Object3D {
    [key: string]: any;
}

export class IFCLoader extends Loader {
    constructor(manager?: LoadingManager);
    load(
        url: string,
        onLoad: (ifc: IFC) => void,
        onProgress?: (event: ProgressEvent) => void,
        onError?: (event: ErrorEvent) => void,
    ): IFC;

    parse(data: ArrayBuffer | string): void;
}
```

When I call the setWasmPath() method inside my class like this, as shown previously on the ifcjs-hello-world example (the one which I'm currently following):

```
import { IFCLoader } from "three/examples/jsm/loaders/IFCLoader";
...
    // Sets up the IFC loading
    const ifcLoader = new IFCLoader();
    ifcLoader.setWasmPath("../assets/wasm/");
```

It says to me that it does not exists. Also, as I was talking with another developer, it looks like some sort of issue with webpack also, because it does not work with it. When compiled with all libs in JS integrated with babel on react, it did work.
I got the three/examples from npm, btw. I really dunno if the class representation is lacking on npm or if it was fixed after.

**Comment by agviegas** [comment]
Hey, you are right. For some reason, the IFCLoader.d.ts is missing our methods. But the IFCLoader definitely has those methods, you can check them [here](https://github.com/mrdoob/three.js/blob/89f0b932ae3664a377b09a0c3bf1604fae1980e9/examples/jsm/loaders/IFCLoader.js#L174). It's a problem of the declaration file; I'll ask them to see how to get this solved. In the meantime, you can [check the correct .d.ts](https://github.com/tomvandig/web-ifc-three/blob/main/src/IfcLoader.d.ts) file and copy it to the @types .d.ts.

**Comment by agviegas** [comment]
[This](https://github.com/three-types/three-ts-types/pull/91) should do it!

**Comment by agviegas** [comment]
We are solving this right now, but the API advances so fast that it'll take a while until this is something stable that you can take directly from three.js and have the latests features (that you probably want to have). 

In the meantime, I'd suggest using web-ifc-three or web-ifc-viewer directly, which already have types definitions. I'm using web-ifc-viewer in an angular project and it works well (I'm refining some details these days). Let me know if you have any question regarding this. I'll leave this issue as open, but keep this comment in mind!
