### ISSUE TITLE
 Different wasm file path in Chrome and Firefox

### ISSUE THREAD

**Issue by makinita** [IFCjs/web-ifc-viewer#69]
The integration of web-ifc-viewer in my project works fine in Firefox but not completely in Chrome.

Firefox loads the .wasm file from root: my-project.com/web-ifc.wasm
Chrome loads it prepending "**js/**": my-project.com/js/web-ifc.wasm

Even if I use _setWasmPath('my-dir')_ chrome still prepends "**js/**":
my-project.com/js/my-dir/web-ifc.wasm (chrome)
my-project.com/my-dir/web-ifc.wasm (firefox)

Finally I could resolve it setting _setWasmPath('../')_, so all browsers loads wasm file from root

**Comment by antoniohof** [comment]
This is a web-ifc bug I guess. SetWasmPath is not working properly.

**Comment by agviegas** [comment]
Yep, but don't worry, I'll solve it there!

**Comment by agviegas** [comment]
After some fiddling, we think that the easiest solution is documenting this in the docs as a caveat, as we are reverse engineering the WASM file in order to be able to change the wasm file, and we don't have a lot of control over it! Anyway, let us know of any other suggestions.
