### ISSUE TITLE
Write IFC

### ISSUE THREAD

**Issue by amitpaz** [IFCjs/web-ifc-viewer#70]
Hello, 
I have noticed IFC write in the documentation 
Can you elaborate a bit more on this?

Thanks!

**Comment by agviegas** [comment]
Hey,
web-ifc is already capable of writing, but we haven't developed the API in web-ifc-three for it yet. Right now, our focus is reading everything and being able to create a fully functional viewer. Then, once we have that (which probably is going to be very soon), we'll develop tools to write as well.
