### ISSUE TITLE
clipping bug

### ISSUE THREAD

**Issue by vegarringdal** [IFCjs/web-ifc-viewer#78]
Need to reset clipping/skip when not enabled

**Comment by agviegas** [comment]
Hey, can you provide more detail?

**Comment by vegarringdal** [comment]
Think we discussed this on discord, Long time ago.
But think the clipping was still active when I disabled clipping.

**Comment by agviegas** [comment]
This should be already solved then, if you deactivate clipping, it hides all clipping planes and un-clips the models. 🙂

**Comment by vegarringdal** [comment]
ok, lets close this one then 👍
