### ISSUE TITLE
How to load multiple files

### ISSUE THREAD

**Issue by themodmin** [IFCjs/web-ifc-viewer#80]
i have multiple files coming out of my Revit file for different treads and all of them share the same coordination point, is it possible to modify the code to load more than one model into the viewer?

**Comment by agviegas** [comment]
Hey, we are already able to open multiple models. Just opening them one after the other should work. Batch opening should be a matter of configuring the input html element!

**Comment by vegarringdal** [comment]
You need to add `multiple` attribute to input and loop the files after.
Thats what I do in https://github.com/vegarringdal/web-ifc-experiment
Dunno if web-ifc-viewer still keeps files open ? That might be a issue...

**Comment by agviegas** [comment]
This is something the library can already do, simply loading multiple files without closing the scene.
