### ISSUE TITLE
Error opening a file

### ISSUE THREAD

**Issue by PeterMoresco** [IFCjs/web-ifc-viewer#83]
Hi, when trying to open some files, I was unable to open the file 202107010001_berlin_schoeneweide_2001.ifc, avaible in [here](http://openifcmodel.cs.auckland.ac.nz/). The following error appeared in the console.

![image](https://user-images.githubusercontent.com/38358731/125838156-2d697ae9-5538-4231-9114-e09af8aa34e8.png)

I tried in Firefox and Edge(Chromium based) and both presented the same errors.

**Comment by agviegas** [comment]
Hey, unfortunately we only support IFC2x3 and IFC4, and this file appears to be in an older version. I could not open it in other apps like BIMvision, so I don't think we'll be able to open it. Anyway, if you try a more modern file, it should work 😄
