### ISSUE TITLE
Incorrect handling of aspect ratio change during onResize

### ISSUE THREAD

**Issue by pablo-mayrgundter** [IFCjs/web-ifc-viewer#84]
The handling of onResize in web-ifc-viewer is flaky:
  - when I manually drag the window to change sizes, the aspect ratio changes mostly work, though it looks a little jittery.
  - but when I just toggle the jsconsole, I reliably get a squashing effect.  This is undone and correst ratio restored when I then close it.

It looks like this problem is only in web-ifc-viewer, as the same steps don't reproduce it in web-ifc-three.

A brief code inspection (and added console loggings as shown in screens below) shows that the resize methods are being called in Viewer, but they're handled separately, in camera.ts and renderer.ts.  So maybe this a race condition during event propagation?  Consolidating the handling in a single method might fix this.

Actual:
![image](https://user-images.githubusercontent.com/2480879/127833412-b1cbd8a5-9605-4af9-93e7-0b93e9a410ef.png)
![image](https://user-images.githubusercontent.com/2480879/127833460-a6e16adb-1bac-40ee-a8fd-f0345e1e6dba.png)

Expected (from web-ifc-three):
![image](https://user-images.githubusercontent.com/2480879/127833240-8e716e25-c428-4a40-a909-12b7a1ab9f42.png)
![image](https://user-images.githubusercontent.com/2480879/127833265-0a678369-89c8-471d-8071-94f3c5d42224.png)

**Comment by harrycollin** [comment]
Hey @pablo-mayrgundter, I managed to fix this in 1.0.35. I'm taking the dimensions from the canvas's container element instead.
Check this here: https://github.com/IFCjs/web-ifc-viewer/blob/5da750f9d9f95eb31dba9b6d735902ee00840bb4/viewer/src/components/context/context.ts#L63
