### ISSUE TITLE
Error loading ifc. RuntimeError: abort(Assertion failed: false, at: ./src/wasm/include/web-ifc.h,618,GetSetArgument). Build with -s ASSERTIONS=1 for more info.

### ISSUE THREAD

**Issue by sbstnkll** [IFCjs/web-ifc-viewer#85]
I try to load a ifc file locally. All other IFC files are loading like a charm, except of this one "walls.ifc":

![image](https://user-images.githubusercontent.com/31189168/129555779-469a6793-1f0e-46b9-b48e-dbff3beccf26.png)

This is the ifc-file: https://www.icloud.com/iclouddrive/0Ixsllj8YKscSypdfNfpmZrMQ#walls

Appreciate any help.

**Comment by agviegas** [comment]
Can you move this issue to [web-ifc](https://github.com/tomvandig/web-ifc)? Thank you!

**Comment by sbstnkll** [comment]
> Can you move this issue to [web-ifc](https://github.com/tomvandig/web-ifc)? Thank you!

done.
