### ISSUE TITLE
Model shakes and geometries clipped

### ISSUE THREAD

**Issue by Hildreya** [IFCjs/web-ifc-viewer#86]
Hi,

When I open a specific file I have some problems with geometries (clipped). Also the model shakes and returns to normal when I stop moving the camera.

To illustrate my problem I opened this file with BIM Vision. 

Result on BIM Vision :
![BIM Vision](https://media.giphy.com/media/EsXWXOQXjkW0WkGuav/giphy.gif)

Result on web-ifc-viewer :
![Web IFC Viewer](https://media.giphy.com/media/LjTBBRLdB6clp6gQt6/giphy.gif)

I sent my file to @agviegas in private.

I tested on Firefox and Chrome and the problem is the same

**Comment by agviegas** [comment]
Solved in `1.0.46`!

The problem is due to the location of the model (very far away from the origin). You can bring the model to the center of the 3d scene using the following code: 

```js
viewer.IFC.applyWebIfcConfig({
  COORDINATE_TO_ORIGIN: true,
  USE_FAST_BOOLS: true
});
```

**Comment by time-to-beem** [comment]
What if we want the model to be geolocalized and not to shake ?

**Comment by agviegas** [comment]
In that case, you will need to either bring the model to the origin and apply the same transformation to the rest of objects / displayed coordinates in your app, or use an alternative solution (maybe three.js logarithmic renderer?). Anyway, this is not an IFC.js-specific issue, but a three.js (and 3D in general) issue. Nummerical stability is present in all 3D software, and tricks like bringing everything to the origin are common in many apps.
