### ISSUE TITLE
 WebAssembly.instantiate(): memory import 47 has a larger maximum size 65536 than the module's declared maximum 32768)

### ISSUE THREAD

**Issue by simpleSketche** [IFCjs/web-ifc-viewer#87]
WebAssembly.instantiate(): memory import 47 has a larger maximum size 65536 than the module's declared maximum 32768)
![error](https://user-images.githubusercontent.com/71196100/131254433-f9afc0c7-adce-421a-ac56-11edb8309428.jpg)

**Comment by agviegas** [comment]
Sounds like you updated the library but didn't update the WASM file. 🙂
