### ISSUE TITLE
Webpack - Critical Dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by VLegatus** [IFCjs/web-ifc-viewer#88]
Webpack throws this warning every compile:
Critical dependency: the request of a dependency is an expression

While I can ignore it with exprContextCritical: false inside the module, the consensus in the webpack issue seemed to be that there's an issue in the dependency where every file in a path is being imported.

The issue in question:
[https://github.com/webpack/webpack/issues/196](https://github.com/webpack/webpack/issues/196)

**Comment by agviegas** [comment]
Hey, unfortunately, that problem appears in the code autogenerated by emscripten to make the glue code necessary for webassembly to work (`web-ifc.api`). Although that code can't be changed, all those statements refer to Node modules, so it shouldn't change anything in the final bundle (it's a false positive).

**Comment by VLegatus** [comment]
Oh, that's a shame.
Thanks!!
