### ISSUE TITLE
Non blocking thread doesn't provide progress information

### ISSUE THREAD

**Issue by cesarecaoduro** [IFCjs/web-ifc-viewer#98]
The IFC worker works fine in avoiding the main window to be blocked, but doesn't provide any feedback on the loading process.
```
viewer.IFC.loader.ifcManager.useWebWorkers(true, 'dist/IFCWorker.js');
```
So the user really doesn't know what is going on :)
![2021-12-01 07_29_06-](https://user-images.githubusercontent.com/26373891/144123212-e9044d51-ad43-48c5-a5ae-a0979ff55de1.jpg)

**Comment by agviegas** [comment]
Now it does! Try using [this](https://ifcjs.github.io/info/docs/Guide/web-ifc-three/api#setonprogress).
